apiVersion: v1
kind: Namespace
metadata:
  name: dgraph
---
apiVersion: v1
kind: Service
metadata:
  name: dgraph
  namespace: dgraph
  labels:
    app: dgraph
spec:
  type: NodePort
  ports:
  - name: alpha
    port: 8080
    targetPort: 8080
    nodePort: 32002
  - name: zero
    port: 9080
    targetPort: 9080
    nodePort: 32004
  - name: ratel
    port: 8000
    targetPort: 8000
    nodePort: 32003
  selector:
    app: dgraph
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgraph
  namespace: dgraph
  labels:
    app: dgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgraph
  template:
    metadata:
      labels:
        app: dgraph
    spec:
      containers:
        - name: dgraph
          image: dgraph/standalone:v20.11.3
          ports:
            - containerPort: 8080
              name: alpha
            - containerPort: 9080
              name: zero
            - containerPort: 8000
              name: ratel