apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: {{ .Values.scheduler.namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: scheduler-plugins-scheduler
      plugins:
        score:
          enabled:
          - name: CommunicationAwareScheduling
      pluginConfig:
      - name: CommunicationAwareScheduling
        args:
          permitWaitingTimeSeconds: 10
          deniedPGExpirationTimeSeconds: 3
